export const SLIDES = [
  {
    num: "01",
    client: "Minimalist",
    category: "Brand Identity · Packaging",
    year: "2025",
    tagline: "Wellness ritual, redefined.",
    bg: "#F7C82A",
    image: "/images/mockup-hero2.jpg",
    mobileImage: "/images/mockup-hero2-mobile.png",
  },
  {
    num: "02",
    client: "GUD MISHRI",
    category: "Brand · Packaging",
    year: "2025",
    tagline: "Precision meets purity.",
    bg: "#7B3FA0",
    image: "/images/mockup-hero3.jpg",
    mobileImage: "/images/mockup-hero3-mobile.png",
  },
  {
    num: "03",
    client: "Womenia",
    category: "Packaging · Graphic",
    year: "2025",
    tagline: "Craft coffee, bold identity.",
    bg: "#F26522",
    image: "/images/mockup-hero4.png",
    mobileImage: "/images/mockup-hero4-mobile.png",
  },
  {
    num: "04",
    client: "Breath of Nature",
    category: "Brand Identity",
    year: "2024",
    tagline: "Nature distilled to essence.",
    bg: "#5DBB46",
    image: "/images/mockup-hero5.png",
    mobileImage: "/images/mockup-hero5-mobile.png",
  },
  {
    num: "05",
    client: "Zovvy",
    category: "Packaging Design",
    year: "2024",
    tagline: "Light, fresh, energized.",
    bg: "#3B9EDC",
    image: "/images/mockup-hero6.jpg",
    mobileImage: "/images/mockup-hero6-mobile.png",
  },
] as const;

export type Slide = (typeof SLIDES)[number];
